services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
    volumes:
      - app/database:db:app/app/database.db

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs