services:
  nodejs:
    image: node:20.18.0
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.24.0
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs